apiVersion: v1
kind: Secret
metadata:
  name: ordering-secrets
stringData:
  ORDERING_DB_USERNAME: ordering
  ORDERING_DB_PASSWORD: ordering
---
apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
stringData:
  RESTAURANT_DB_USERNAME: restaurant
  RESTAURANT_DB_PASSWORD: restaurant
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
stringData:
  NOTIFICATION_DB_USERNAME: notification
  NOTIFICATION_DB_PASSWORD: notification
